######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 25 11:17:39 2012
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += testking.hpp ../lib/constants.hpp ../lib/king.hpp ../lib/piece.hpp
SOURCES += testking.cpp ../lib/king.cpp ../lib/piece.cpp
