######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 25 11:17:39 2012
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += testking.hpp testqueen.hpp ../lib/constants.hpp \
../lib/king.hpp ../lib/queen.hpp ../lib/piece.hpp
SOURCES += testking.cpp testqueen.cpp ../lib/king.cpp ../lib/queen.cpp \
../lib/piece.cpp
