######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 19 01:31:09 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src src/lib
INCLUDEPATH += . src/lib

CONFIG += qt debug

# Input
HEADERS += src/lib/constants.hpp src/lib/piece.hpp
SOURCES += src/main.cpp src/lib/piece.cpp
